### ISSUE TITLE
Error 80160000 - Import Solution Failed: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by dazzletag** [scottdurow/power-drag-drop#14] opened 2022-12-13 12:28 UTC
Hi, I'm trying to import into a Production environment and have set the Power Apps component framework for canvas apps toggle to on. I am a system administrator role in the environment.

I get a failure:

Solution "Power Drag Drop" failed to import: Import Solution Failed: Object reference not set to an instance of an object.

Anything else I should check? I've tried all the managed solutions. 

Cheers

**Comment by scottdurow** [comment] 2022-12-13 16:38
This appears to be caused by a recent update to the Power Apps platform which hopefully should be fixed soon.
Which region are you trying to import into?

**Comment by dazzletag** [comment] 2022-12-13 16:40
Ahh ok -  I'm in the UK.

I did wonder as I tried a few other things and didn't get the same error

**Comment by scottdurow** [comment] 2022-12-13 17:15
The issue is affecting the creator kit as well:
https://github.com/microsoft/powercat-creator-kit/issues/214
https://github.com/microsoft/powercat-code-components/issues/152

I've managed to import into Europe and Canada ok - so I think a fix is rolling out.

**Comment by KhurramJamshed** [comment] 2022-12-14 06:40
> This appears to be caused by a recent update to the Power Apps platform which hopefully should be fixed soon. Which region are you trying to import into?

Just FYI for others that we are having same issue in Australia region too.
hope it gets fixed soon.
Thanks @scottdurow for your valuable contribution, it indeed is looking promising.

**Comment by dazzletag** [comment] 2022-12-17 12:32
Working in UK again :)

**Comment by scottdurow** [comment] 2022-12-29 05:11
I am going to close this now as it seems the issue is fixed. If anyone has the problem again, please add a comment!

**Closed** 2022-12-29 05:11 UTC

**Comment by dKayt** [comment] 2023-07-19 06:35
Hi Scott, unfortunately I have that same issue in Germany. I can't import the last release (power-drag-drop-1.0.27).

**Comment by Harish2127** [comment] 2025-01-20 09:37
@scottdurow I am facing an issue while importing the solution into the Production environment. I was able to upload and customize it in the Development environment without any issues. The error I’m encountering in the Production environment is as follows:

Import Solution Failed: CustomControl with name CustomControl.PowerDragDrop failed to import with error: Principal user (Id=b293e53e-dba9-ee11-be37-6045bd5b399c, type=8, roleCount=5, privilegeCount=1760, accessMode='0 Read-Write', AADObjectId='f01026e8-07f3-408d-9532-6725dd1c7689', MetadataCachePrivilegesCount=5766, businessUnitId=05f38bd5-5ff5-ea11-a815-000d3a8524ff), is missing prvCreateCustomControl privilege (Id=036ed3c6-2dfd-4b98-9271-3bc72cba3586) on OTC=9753 for entity 'customcontrol' (LocalizedName='Custom Control'). context.Caller=b293e53e-dba9-ee11-be37-6045bd5b399c. Consider adding missed privilege to one of the principal (user/team) roles.

I have admin roles for Power Platform. 
Could you please guide me on how to resolve this issue?

**Comment by scottdurow** [comment] 2025-01-20 15:36
Hi @Harish2127 - this is usually caused by importing into the default environment- if so you will need to create a production environment with dataverse. Hope this helps!

**Comment by Harish2127** [comment] 2025-01-21 03:16
@scottdurow Thanks for your reply. In the default environment, I was not assigned the System Administrator role. After being assigned this role, I was able to upload the solution successfully.
